travis:
  secure:
    BINSTAR_TOKEN: PCAnNdVdyQ8jKBWmuJg6PdZUGDOebyvrcytxYT3BE5nYaLmS4FNiYe611NDXBNRmtmaw6AYj/nEs23lpHX/fXu1klHnWYXC1pBs/xVqXXtKNe7qT99lOJCA+fGRvApPdodRtL0iop2RS4JgOTIF6X0DBjK8vI5V+3erqM3TGYewM7pCU/jcwztJKx+jfSnq16xeWe2og7XPt8efaJzxP90j+mRAiItbKnd0A2/99N+3F/ruSYZLyybHkkCN7HhnPaClhS74HCDeonn1zWB1xaEbSOOD/XsBTQnbbLdRDVEyZSLlGYbRTU620pbCG/SODYGDlJ4ae9nSRYi4RdfxNz069BLAFwvoHpyxjv/F1hYgGOOO75mVuEYFGURXHOm7Io4sfEQI1wO3R76EVKcrupFNvA+2fKaC332+3cICue+8cJbhNo93RU/RQVmX9pyAPjFApQMXXRfl9C5sMOxvla+zQltDkLhNznlHTHD22wF+GxoEAg1Ps5PmEHQt3RPoE6JuIrPeHhjQMV2yNKC49OUFfmFZltCFSrpJxVw/jLKMYtu0eAk+WHiBu2UMJdFJ5Q4hEquq9FugxL4wfdshGgOEmgCjwNX2nfZOE2Y4+HaGULZPWxuljxI+ceirNlbOGpmBB+SIsgjjmD+BUsaiKvjFT3hDXQHPkvnOgv54gbYM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
